add_requires("glm")
add_requires("raylib")

target("merker")
    add_packages("glm")
    add_packages("raylib")
    add_defines("PLATFORM_DESKTOP")
    set_kind("binary")
    set_languages("c++23")
    add_files("src/*.cpp")
    set_optimize("fastest")
